-- DDL for currency_exchange_rates database
-- Run this against the target database before deploying the sync job

CREATE TABLE IF NOT EXISTS exchange_rates (
    id              INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    date            DATE NOT NULL,
    timestamp       TIMESTAMP WITH TIME ZONE NOT NULL,
    epoch_seconds   BIGINT NOT NULL,
    base            VARCHAR(5) NOT NULL,
    "to"            VARCHAR(5) NOT NULL,
    rate            DECIMAL NOT NULL,

    PRIMARY KEY (timestamp, base, "to")
);

CREATE INDEX IF NOT EXISTS ix_exchange_rates_id ON exchange_rates (id);
CREATE INDEX IF NOT EXISTS ix_exchange_rates_date ON exchange_rates (date);
CREATE INDEX IF NOT EXISTS ix_exchange_rates_timestamp ON exchange_rates (timestamp);
CREATE INDEX IF NOT EXISTS ix_exchange_rates_epoch_seconds ON exchange_rates (epoch_seconds);
CREATE INDEX IF NOT EXISTS ix_exchange_rates_base ON exchange_rates (base);
CREATE INDEX IF NOT EXISTS ix_exchange_rates_to ON exchange_rates ("to");
