apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Values.cronjob.name }}
  namespace: {{ $.Values.cronjob.metadata.namespace }}
spec:
  concurrencyPolicy: {{ $.Values.cronjob.image.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ $.Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $.Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      name: {{ $.Values.cronjob.name }}
      namespace: {{ $.Values.cronjob.metadata.namespace }}
    spec:
      backoffLimit: {{ $.Values.cronjob.backoffLimit }}
      template:
        metadata:
          name: {{ $.Values.cronjob.name }}
          namespace: {{ $.Values.cronjob.metadata.namespace }}
        spec:
          containers:
          - image: {{ $.Values.cronjob.image.repository }}
            imagePullPolicy: {{ $.Values.cronjob.image.pullPolicy }}
            name: {{ $.Values.cronjob.name }}
            env:
              - name: EXCHANGE_RATES_API_LATEST_RATES_URL
                value: {{ $.Values.cronjob.exchangeRatesApiLatestRatesUrl }}
              - name: RETENTION_PERIOD_DAYS
                value: {{ $.Values.cronjob.retentionPeriodDays | quote }}
              - name: DEPLOYMENT_ENVIRONMENT
                value: {{ $.Values.cronjob.env }}
              - name: LOG_LEVEL
                value: {{ $.Values.cronjob.logLevel }}
              - name: CODE_VERSION
                value: {{ $.Values.cronjob.version }}
              - name: EXCHANGE_RATES_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cronjob.metadata.secret }}
                    key: exchangeRatesAPIKey
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cronjob.metadata.secret }}
                    key: postgresSqlDbHost
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cronjob.metadata.secret }}
                    key: postgresSqlDbPort
              - name: DB_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cronjob.metadata.secret }}
                    key: postgresSqlDbName
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cronjob.metadata.secret }}
                    key: postgresSqlDbUser
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cronjob.metadata.secret }}
                    key: postgresSqlDbPassword
              - name: DB_SSL_MODE
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cronjob.metadata.secret }}
                    key: postgresSqlSslMode
              - name: ROLLBAR_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.cronjob.metadata.secret }}
                    key: rollbarToken
            resources:
              requests:
                memory: {{ $.Values.cronjob.resources.requests.memory }}
                cpu: {{ $.Values.cronjob.resources.requests.cpu }}
              limits:
                memory: {{ $.Values.cronjob.resources.limits.memory }}
                cpu: {{ $.Values.cronjob.resources.limits.cpu }}

          dnsPolicy: ClusterFirst
          restartPolicy: {{ $.Values.cronjob.image.restartPolicy }}
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          imagePullSecrets:
            - name: {{ $.Values.cronjob.image.imagePullSecrets }}
  schedule: {{ quote $.Values.cronjob.schedule }}
  timeZone: {{ $.Values.cronjob.timeZone }}
  suspend: false
---
