apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Values.cronjob.name }}
  namespace: {{ $.Values.cronjob.metadata.namespace }}
spec:
  concurrencyPolicy: {{ $.Values.cronjob.image.concurrencyPolicy }}
  successfulJobsHistoryLimit: 25
  failedJobsHistoryLimit: 100
  jobTemplate:
    metadata:
      name: {{ $.Values.cronjob.name }}
      namespace: {{ $.Values.cronjob.metadata.namespace }}
    spec:
      template:
        metadata:
          name: {{ $.Values.cronjob.name }}
          namespace: {{ $.Values.cronjob.metadata.namespace }}
        spec:
          containers:
          - image: {{ $.Values.cronjob.image.repository }}
            imagePullPolicy: {{ $.Values.cronjob.image.pullPolicy }}
            name: {{ $.Values.cronjob.name }}
            env:
              - name: DEPLOYMENT_ENVIRONMENT
                value: {{ $.Values.cronjob.env }}
              - name: CODE_VERSION
                value: {{ $.Values.cronjob.version }}
              - name: EXCHANGE_RATES_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: sync-job
                    key: exchangeRatesAPIKey
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: sync-job
                    key: postgresSqlDbHost
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: sync-job
                    key: postgresSqlDbPort
              - name: DB_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: sync-job
                    key: postgresSqlDbName
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: sync-job
                    key: postgresSqlDbUser
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: sync-job
                    key: postgresSqlDbPassword
              - name: ROLLBAR_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: sync-job
                    key: rollbarToken
            resources:
              requests:
                memory: {{ $.Values.cronjob.resources.requests.memory }}
                cpu: {{ $.Values.cronjob.resources.requests.cpu }}
              limits:
                memory: {{ $.Values.cronjob.resources.limits.memory }}
                cpu: {{ $.Values.cronjob.resources.limits.cpu }}

          dnsPolicy: ClusterFirst
          restartPolicy: {{ $.Values.cronjob.image.restartPolicy }}
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          imagePullSecrets:
            - name: {{ $.Values.cronjob.image.imagePullSecrets }}
  schedule: {{ quote $.Values.cronjob.schedule }}
  timeZone: {{ $.Values.cronjob.timeZone }}
  suspend: false
---
