cronjob:
  name: currency-exchange-sync-fixed-eight-hour-cron
  schedule: "0 0,8,16 * * *"
  id: currency-exchange-sync-fixed-eight-hour-cron
  timeZone: "Asia/Kolkata"
  exchangeRatesApiLatestRatesUrl: http://api.exchangeratesapi.io/v1/latest
  retentionPeriodDays: 400
  env: Production
  logLevel: INFO
  version: "1.4-prod"

  metadata:
    namespace: currency-exchange-sync
    creationTimestamp: null

  restartPolicy: Never
  backoffLimit: 1
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 10

  image:
    repository: registry.digitalocean.com/aneeshneelam-container-registry-sfo3/currency-exchange-sync
    pullPolicy: Always
    imagePullSecrets: aneeshneelam-container-registry-sfo3
    restartPolicy: Never
    concurrencyPolicy: Forbid

  resources:
    requests:
      cpu: 10m
      memory: 8Mi
    limits:
      cpu: 100m
      memory: 16Mi
