cronjob:
  name: currency-exchange-sync-fixed-eight-hour-cron
  schedule: "0 0,8,16 * * *"
  id: currency-exchange-sync-fixed-eight-hour-cron
  timeZone: "Asia/Kolkata"

  metadata:
    namespace: currency-exchange-sync
    creationTimestamp: null

  restartPolicy: Never

  image:
    repository: registry.digitalocean.com/aneeshneelam-container-registry-sfo3/currency-exchange-sync
    pullPolicy: IfNotPresent
    imagePullSecrets: aneeshneelam-container-registry-sfo3
    restartPolicy: Never
    concurrencyPolicy: Forbid

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
