cronjob:
  name: currency-exchange-rates-sync
  schedule: "0 0,3,6,9,12,15,18,21 * * *"
  id: currency-exchange-rates-sync
  timeZone: "Asia/Kolkata"
  exchangeRatesApiLatestRatesUrl: http://api.exchangeratesapi.io/v1/latest
  retentionPeriodDays: 400
  env: Production
  logLevel: INFO
  version: "2.0-prod"

  metadata:
    namespace: currency-exchange-sync
    secret: sync-job

  restartPolicy: Never
  backoffLimit: 1
  successfulJobsHistoryLimit: 8
  failedJobsHistoryLimit: 8

  image:
    repository: registry.digitalocean.com/aneeshneelam-container-registry-sfo3/currency-exchange-sync
    pullPolicy: Always
    imagePullSecrets: aneeshneelam-container-registry-sfo3
    restartPolicy: Never
    concurrencyPolicy: Forbid

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
